# config/packages/security.yaml
security:
  # 1) Hashers
  password_hashers:
    App\Entity\User:
      algorithm: auto

  # 2) User provider : on ne pointe plus sur Client mais sur User
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  # 3) Firewalls
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\AppAuthenticator
      logout:
        path: app_logout
      # si tu veux le remember_me
      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800 # 1 semaine

  # 4) Access control
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/dashboard, roles: ROLE_USER }
    - { path: ^/bids, roles: ROLE_USER }
    - { path: ^/purchase, roles: ROLE_USER }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: PUBLIC_ACCESS }

  # 5) Roles hierarchy (facultatif)
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
